export const TASKS_REDUCER_ADD_TASK = 'TASKS-REDUCER-ADD-TASK';
export const TASKS_REDUCER_REMOVE_TASK = 'TASKS-REDUCER-REMOVE-TASK';
export const TASKS_REDUCER_UPDATE_TASK = 'TASKS-REDUCER-UPDATE-TASK';
export const TASKS_REDUCER_SET_TASKS = 'TASKS-REDUCER-SET-TASKS';
export const TASKS_REDUCER_CHANGE_TASK_ENTITY_STATUS = 'TASKS-REDUCER-CHANGE-TASK-ENTITY-STATUS';

export const TASKS_SAGA_GET_TASKS = 'TASKS-SAGA-GET-TASKS';
export const TASKS_SAGA_DELETE_TASK = 'TASKS-SAGA-DELETE-TASK';
export const TASKS_SAGA_ADD_TASK = 'TASKS-SAGA-ADD-TASK';
export const TASKS_SAGA_UPDATE_TASK = 'TASKS-SAGA-UPDATE-TASK';
