export const APP_SAGA_INITIALIZE = 'APP-SAGA-INITIALIZE-APP';

export const APP_REDUCER_CHANGE_STATUS = 'APP-REDUCER-CHANGE-STATUS';
export const APP_REDUCER_SET_APP_ERROR = 'APP-REDUCER-SET-APP-ERROR';
export const APP_REDUCER_SET_APP_INITIALIZE = 'APP-REDUCER-SET-APP-INITIALIZE';
