export const TODOLISTS_REDUCER_REMOVE_TODOLIST = 'TODOLISTS-REDUCER-REMOVE-TODOLIST';
export const TODOLISTS_REDUCER_ADD_TODOLIST = 'TODOLISTS-REDUCER-ADD-TODOLIST';
export const TODOLISTS_REDUCER_CHANGE_TODOLIST_TITLE = 'TODOLISTS-REDUCER-CHANGE-TODOLIST-TITLE';
export const TODOLISTS_REDUCER_CHANGE_TODOLIST_FILTER = 'TODOLISTS-REDUCER-CHANGE-TODOLIST-FILTER';
export const TODOLISTS_REDUCER_SET_TODOLISTS = 'TODOLISTS-REDUCER-SET-TODOLISTS';
export const TODOLISTS_REDUCER_CHANGE_TODOLIST_ENTITY_STATUS =
  'TODOLISTS-REDUCER-CHANGE-TODOLIST-ENTITY-STATUS';

export const TODOLISTS_SAGA_GET_TODOLISTS = 'TODOLISTS-SAGA-GET-TODOLISTS';
export const TODOLISTS_SAGA_CREATE_TODOLIST = 'TODOLISTS-SAGA-CREATE-TODOLIST';
export const TODOLISTS_SAGA_REMOVE_TODOLIST = 'TODOLISTS-SAGA-REMOVE-TODOLIST';
export const TODOLISTS_SAGA_CHANGE_TODOLIST_TITLE = 'TODOLISTS-SAGA-CHANGE-TODOLIST-TITLE';
